### ISSUE TITLE
是否跟随 Debian 维护的版本？

### ISSUE THREAD

**Issue by hosiet** [man-pages-zh/man2html#1]
现在 fork 的版本较旧，源代码也不清晰。Debian 对其进行了重新打包：https://packages.debian.org/sid/man2html-base

这个包不包含 CGI 等用不上的东西，而且有不少补丁。可以考虑跟随这个版本进行工作。

**Comment by da-liii** [comment]
有空就做吧！

**Comment by hosiet** [comment]
已经基本上合并完成了，采用的是在上游源代码基础上打补丁，再合并当前`master`分支修改的方式。剩下一些大写标签改小写的工作，不过这不是必需的工作。现在已经可以考虑改变开发用分支了。

另外，建议不要在代码内修改默认安装路径，可以在使用 autoconf 在安装时修改，例如`./configure --prefix=~/software`
